server:
  port: 9000
spring:
  application:
    name: service-consumer
  cloud:
    discovery:
      locator:
        enabled: false
    consul:
      # \u6307\u5B9Aconsul\u7684ip\u5730\u5740\u548C\u7AEF\u53E3
      host: 192.168.80.130
      port: 8500
      discovery:
        # \u6307\u5B9A\u670D\u52A1\u7248\u672C\u4FE1\u606F
        tags: version=1.0,auth=Mr.Kong
        # \u662F\u5426\u9700\u8981\u6CE8\u518C\u5230consul\uFF0C\u9ED8\u8BA4\u4E3Atrue
        register: true
        # \u6CE8\u518C\u7684\u5B9E\u4F8BID (\u552F\u4E00\u6807\u5FD7)
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        # \u670D\u52A1\u540D\u79F0
        service-name: ${spring.application.name}
        # \u670D\u52A1\u8BF7\u6C42\u7AEF\u53E3
        port: ${server.port}
        # \u6307\u5B9A\u5F00\u542Fip\u5730\u5740\u6CE8\u518C
        prefer-ip-address: true
        # \u5F53\u524D\u670D\u52A1\u8BF7\u6C42ip
        ip-address: ${spring.cloud.client.ip-address}
        # \u6307\u5B9Aconsul\u5FC3\u8DF3\u68C0\u6D4B\u5730\u5740
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
        # \u6307\u5B9Aconsul\u5FC3\u8DF3\u68C0\u6D4B\u95F4\u9694
        health-check-interval: 15s